version: "3"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: mysecretpassword1234
    networks:
      - barcelona_network
    volumes:
      - .:/barcelona
    tty: true
    stdin_open: true
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    links:
      - db
  db:
    image: postgres:10.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword1234
    networks:
      - barcelona_network
    volumes:
      - ./docker/mysql:/var/lib/mysql
networks:
  barcelona_network:
    external: true
